import GlobalContext from "@/context";
import Head from "next/head";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
        />
      </Head>
      <GlobalContext>
        <body className="relative w-screen h-screen transition-all">
          {children}
        </body>
      </GlobalContext>
    </html>
  );
}
