import "../styles/global.css";
import TaskBar from "../components/taskBar";
import MusicBar from "../components/musicBar";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

interface PropsMenu {
  name: string;
  url: string;
  icon: HTMLImageElement;
}
export default function Home() {
  return (
    <div className="relative flex justify-center bg-[#7F7FD5] bg-app h-screen font-bold">
      <TaskBar />
      <MusicBar />
    </div>
  );
}
