import "../styles/global.css";
import TaskBar from "../components/taskBar";
import MusicBar from "../components/musicBar";
import Portfolio from "@/components/portfolio";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

interface PropsMenu {
  name: string;
  url: string;
  icon: HTMLImageElement;
}
export default function Home() {
  return (
    <div className="relative flex justify-center  bg-[#09090a]   h-screen font-bold">
      <Portfolio />
      <TaskBar />
      <MusicBar />
    </div>
  );
}
